# Generated by Django 5.0.1 on 2026-01-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("CARDIOLOGY", "Cardiology"),
                            ("NEUROLOGY", "Neurology"),
                            ("ORTHOPEDICS", "Orthopedics"),
                            ("PEDIATRICS", "Pediatrics"),
                            ("GYNECOLOGY", "Gynecology"),
                            ("DERMATOLOGY", "Dermatology"),
                            ("PSYCHIATRY", "Psychiatry"),
                            ("GENERAL", "General Medicine"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=255)),
                (
                    "experience_years",
                    models.IntegerField(help_text="Years of experience"),
                ),
                ("qualification", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "db_table": "doctors",
                "ordering": ["-created_at"],
            },
        ),
    ]
